### ISSUE TITLE
Share godot and mono runtime version

### ISSUE THREAD

**Issue by GeorgeS2019** [caemanswartz/SharpScapeGodotGame#2]
I recently tried to export to HTML5 using the latest Godot 3.5x mono and I get this [error](https://github.com/godotengine/godot-proposals/discussions/4709). 

Could you please share which Godot version you used and the mono runtime you installed.

Do you have plan to use Godot4 mono custom build?

**Comment by caemanswartz** [comment]
The current projects are using Godot3.4.4 and compiled using the dotnetcli. Right now there is no plan to use Godot4. I have heard that c# in godot4 is a little iffy at them moment and needs some more work. I am interested in the new tilemapping tools but it will have to wait until version 4 has a stable release.
