### ISSUE TITLE
TileMap script is slow

### ISSUE THREAD

**Issue by cptchuckles** [caemanswartz/SharpScapeGodotGame#33]
Running regex on all of the tiles causes HTML5 export to hang for a good 20-30 seconds when loading the world.  I tried it without the script attached to the tilemap, and it loads in a fraction of a second, so the script either needs to be seriously optimized, or removed.

If a dictionary can be used to lookup tiles instead of testing strings by regex, that would speed things up considerably.

**Comment by caemanswartz** [comment]
Overall the autotile just doesn't seem like it is built for this kind of map building. It should probably just be converted into normal tiles and placed manually.
